# Generated by Django 5.2.2 on 2025-06-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_mmain_post_blog_main_post_alter_blog_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='home/images/feature_image/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Trending', 'Trending'), ('Recent', 'Recent'), ('Publish', 'Publish')], default='Recent', max_length=200),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('0', 'DRAFT'), ('1', 'PUBLISH')], default=0, max_length=1),
        ),
    ]
