# Generated by Django 5.2.2 on 2025-06-07 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_blog_section_alter_blog_status_navigationitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Trending', 'Trending'), ('Publish', 'Publish'), ('Recent', 'Recent')], default='Recent', max_length=200),
        ),
        migrations.DeleteModel(
            name='NavigationItem',
        ),
    ]
