# Generated by Django 5.2.2 on 2025-06-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_blog_meta_keyword_blog_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='section',
            field=models.CharField(choices=[('Popular', 'Popular'), ('Trending', 'Trending'), ('Recent', 'Recent')], default='Recent', max_length=200),
        ),
    ]
